In [1]:
import torch
torch.__version__

'2.2.1+cu121'

In [2]:
torch.cuda.is_available()

True

초기화 되지 않은 텐서

In [4]:
x = torch.empty(4, 2)
print(x)

tensor([[-1.0034e+28,  4.5558e-41],
        [-1.0034e+28,  4.5558e-41],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


무작위로 초기화된 텐서

In [6]:
x = torch.rand(4, 2)
print(x)

tensor([[0.1095, 0.9658],
        [0.5244, 0.5886],
        [0.8039, 0.4654],
        [0.0724, 0.5272]])


데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [7]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [8]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


2 x 4 크기, double 타입, 1로 채워진 텐서

In [9]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


x와 같은 크기, float 타입, 무작위로 채워진 텐서

In [12]:
x = torch.randn_like(x,  dtype=torch.float)   # 타입이 없으면 기존의 데이터 타입을 사용
print(x)

tensor([[-0.1577, -0.6200,  0.0342, -0.6649],
        [-0.1198,  1.2049, -0.6119,  0.9285]])


텐서의 크기 계산

In [13]:
print(x.size())

torch.Size([2, 4])


데이터 타입

In [14]:
tf = torch.FloatTensor([1,2,3])
print(tf)
print(tf.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
# 타입 캐스팅 
print(tf.short())
print(tf.int())
print(tf.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [17]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [18]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


CUDA Tensors

In [21]:
x = torch.randn(1)      # 1개의 랜덤한 숫자
print(x)
print(x.item())         # 숫자만 뽑아내기
print(x.dtype)          # 데이터 타입 확인

tensor([0.8720])
0.8719654679298401
torch.float32


In [23]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # GPU 사용 가능 여부 확인
print(device) 
y = torch.ones_like(x, device=device)  # CPU/GPU에 Tensor 생성
x = x.to(device)    # CPU/GPU에 Tensor 이동
print(x)
z = x + y
print(z)
print(z.to("cpu", torch.double)) # CPU로 이동하면서 데이터 타입 변경

cpu
tensor([0.8720])
tensor([1.8720])
tensor([1.8720], dtype=torch.float64)


다차원 텐서 표현

In [24]:
# 0D Tensor(Scalar)
t0 = torch.tensor(0)
print(t0)
print(t0.ndim)
print(t0.shape)

tensor(0)
0
torch.Size([])


In [25]:
# 1D Tensor(Vector)
t1 = torch.tensor([1,2,3])
print(t1)
print(t1.ndim)
print(t1.shape)

tensor([1, 2, 3])
1
torch.Size([3])


In [27]:
# 2D Tensor(Matrix)
t2 = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(t2)
print(t2.ndim)
print(t2.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [31]:
# 3D Tensor
t3 = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print(t3)
print(t3.ndim)
print(t3.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([3, 3, 3])


In [32]:
# 4D Tensor
t4 = torch.tensor([[[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]], 
                  [[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]],
                  [[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]]])
print(t4)
print(t4.ndim)
print(t4.shape)

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
4
torch.Size([3, 3, 3, 3])
