### 텐서의 연산(Operations)

* 텐서에 대한 수학 연산, 삼각함수, 비트 연산, 비교 연산, 집계 등 제공

In [3]:
import torch
import math

a = torch.rand(1, 2) * 2 - 1                # 랜덤값 생성
print(a)
print(torch.abs(a))                         # 절대값
print(torch.floor(a))                       # 내림
print(torch.clamp(a, min=-0.5, max=0.5))    # 최소값과 최대값 사이의 값으로 제한  

tensor([[-0.7195,  0.1912]])
tensor([[0.7195, 0.1912]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.1912]])


In [4]:
print(a)
print(torch.min(a))                         # 최소값
print(torch.max(a))                         # 최대값
print(torch.mean(a))                        # 평균값
print(torch.sum(a))                         # 합계
print(torch.prod(a))                        # 곱
print(torch.std(a))                         # 표준편차
print(torch.var(a))                         # 분산
print(torch.median(a))                      # 중앙값
print(torch.mode(a))                        # 최빈값
print(torch.norm(a))                        # 노름
print(torch.dist(a, torch.zeros(1, 2)))     # 두 텐서 사이의 거리
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8]))) # 중복 제거

tensor([[-0.7195,  0.1912]])
tensor(-0.7195)
tensor(0.1912)
tensor(-0.2642)
tensor(-0.5283)
tensor(-0.1375)
tensor(0.6439)
tensor(0.4147)
tensor(-0.7195)
torch.return_types.mode(
values=tensor([-0.7195]),
indices=tensor([0]))
tensor(0.7445)
tensor(0.7445)
tensor([1, 2, 3, 4, 5, 6, 7, 8])


max와 min은 dim 인자를 줄 경우 argmax와 argmin도 함께 리턴
* argmax: 최대값을 가진 인덱스
* argmin: 최소값을 가진 인덱스

In [7]:
x = torch.rand(2, 2)
print(x)
print(x.max(dim=0))                         # 열 단위 최대값
print(x.max(dim=1))                         # 행 단위 최대값

tensor([[0.5459, 0.9910],
        [0.5144, 0.4479]])
torch.return_types.max(
values=tensor([0.5459, 0.9910]),
indices=tensor([0, 0]))
torch.return_types.max(
values=tensor([0.9910, 0.5144]),
indices=tensor([1, 0]))


In [9]:
print(x)
print(x.min(dim=0))                         # 열 단위 최소값
print(x.min(dim=1))                         # 행 단위 최소값

tensor([[0.5459, 0.9910],
        [0.5144, 0.4479]])
torch.return_types.min(
values=tensor([0.5144, 0.4479]),
indices=tensor([1, 1]))
torch.return_types.min(
values=tensor([0.5459, 0.4479]),
indices=tensor([0, 1]))


임의의 랜덤 텐서

In [10]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.7219, 0.7033],
        [0.9453, 0.0754]])
tensor([[0.4403, 0.7461],
        [0.9989, 0.3223]])


torch.add: 덧셈

In [12]:
print(x + y)
print(torch.add(x, y))                      # 덧셈

tensor([[1.1622, 1.4495],
        [1.9442, 0.3978]])
tensor([[1.1622, 1.4495],
        [1.9442, 0.3978]])


결과 텐서를 인자로 제공

In [14]:
result = torch.empty(2, 2)
torch.add(x, y, out=result)
print(result)

tensor([[1.1622, 1.4495],
        [1.9442, 0.3978]])


in-place 방식
* in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
* x.copy_(y), x.t_()

In [20]:
print(x)
print(y)
y.add_(x)                                   # y와 x를 덧셈 후 다시 y에 대입
print(y)

tensor([[0.7219, 0.7033],
        [0.9453, 0.0754]])
tensor([[1.8841, 2.1528],
        [2.8895, 0.4732]])
tensor([[2.6059, 2.8561],
        [3.8347, 0.5486]])


torch.sub: 뺄셈

In [16]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))                      # 뺄셈
print(x.sub(y))                            # x에서 y를 뺀 결과를 반환

tensor([[0.7219, 0.7033],
        [0.9453, 0.0754]])
tensor([[1.1622, 1.4495],
        [1.9442, 0.3978]])
tensor([[-0.4403, -0.7461],
        [-0.9989, -0.3223]])
tensor([[-0.4403, -0.7461],
        [-0.9989, -0.3223]])
tensor([[-0.4403, -0.7461],
        [-0.9989, -0.3223]])


torch.mul: 곱셉
torch.div: 나눗셈

In [21]:
print(x)
print(y)
print(x * y)
print(torch.mul(x, y))  # 곱셈
print(x.mul(y))         # x와 y를 곱한 결과를 반환 

print(x / y)
print(torch.div(x, y)) # 나눗셈
print(x.div(y))        # x를 y로 나눈 결과를 반환

tensor([[0.7219, 0.7033],
        [0.9453, 0.0754]])
tensor([[2.6059, 2.8561],
        [3.8347, 0.5486]])
tensor([[1.8812, 2.0088],
        [3.6249, 0.0414]])
tensor([[1.8812, 2.0088],
        [3.6249, 0.0414]])
tensor([[1.8812, 2.0088],
        [3.6249, 0.0414]])
tensor([[0.2770, 0.2463],
        [0.2465, 0.1375]])
tensor([[0.2770, 0.2463],
        [0.2465, 0.1375]])


torch.mm: 내적(dot product)

In [22]:
print(x)
print(y)
print(torch.matmul(x, y))    # 행렬 곱셈
z = torch.mm(x, y)           # 행렬 곱셈
print(z)
print(torch.svd(z))          # 특이값 분해


tensor([[0.7219, 0.7033],
        [0.9453, 0.0754]])
tensor([[2.6059, 2.8561],
        [3.8347, 0.5486]])
tensor([[4.5783, 2.4476],
        [2.7526, 2.7412]])
tensor([[4.5783, 2.4476],
        [2.7526, 2.7412]])
torch.return_types.svd(
U=tensor([[-0.8042, -0.5943],
        [-0.5943,  0.8042]]),
S=tensor([6.4205, 0.9053]),
V=tensor([[-0.8283, -0.5603],
        [-0.5603,  0.8283]]))
