텐서의 조작(Manipulations)
* 인덱싱(Indexing): NumPy처럼 인덱싱 형태로 사용가능

In [2]:
import torch

In [6]:
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

print(x[0, 0])
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])

print(x[:, 0])
print(x[:, 1])

print(x[0, :])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


`view`: 텐서의 크기(size)나 모양(shape)을 변경

- 기본적으로 변경 전과 후에 텐서 안의 원소 개수가 유지되어야 함
- -1로 설정되면 계산을 통해 해당 크기값을 유추

In [9]:
x = torch.randn(4, 5)
print(x)
y = x.view(20)        # 1차원 벡터로 변환
print(y)
z = x.view(5, -1)     # 5행으로 변환
print(z)

tensor([[ 0.1943,  0.6296, -0.7337, -0.3751, -0.0564],
        [-0.9165,  0.3038, -0.3002, -1.3597, -1.2562],
        [-0.8852,  1.8245,  1.3540, -0.7835,  0.4631],
        [ 1.3937, -1.0983,  1.1972,  2.1487, -0.3287]])
tensor([ 0.1943,  0.6296, -0.7337, -0.3751, -0.0564, -0.9165,  0.3038, -0.3002,
        -1.3597, -1.2562, -0.8852,  1.8245,  1.3540, -0.7835,  0.4631,  1.3937,
        -1.0983,  1.1972,  2.1487, -0.3287])
tensor([[ 0.1943,  0.6296, -0.7337, -0.3751],
        [-0.0564, -0.9165,  0.3038, -0.3002],
        [-1.3597, -1.2562, -0.8852,  1.8245],
        [ 1.3540, -0.7835,  0.4631,  1.3937],
        [-1.0983,  1.1972,  2.1487, -0.3287]])


`item`: 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음

In [10]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.6408])
-0.6407829523086548
torch.float32


스칼라값 하나만 존재해야 item() 사용 가능

In [13]:
x = torch.randn(2)
print(x)
print(x[0].item())

tensor([0.6507, 0.0102])
0.6506795287132263


`squeeze`: 차원을 축소(제거)

In [14]:
tensor = torch.rand(1, 3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.1139, 0.1809, 0.3196],
         [0.7609, 0.3725, 0.6431],
         [0.2002, 0.5584, 0.6522]]])
torch.Size([1, 3, 3])


In [15]:
t =  tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.1139, 0.1809, 0.3196],
        [0.7609, 0.3725, 0.6431],
        [0.2002, 0.5584, 0.6522]])
torch.Size([3, 3])


`unsqueeze`: 차원을 증가(생성)

In [17]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.9325, 0.8777, 0.6783],
        [0.6428, 0.5617, 0.9886],
        [0.2350, 0.2097, 0.6549]])
torch.Size([3, 3])


In [19]:
tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.9325, 0.8777, 0.6783],
         [0.6428, 0.5617, 0.9886],
         [0.2350, 0.2097, 0.6549]]])
torch.Size([1, 3, 3])


In [20]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.9325],
         [0.8777],
         [0.6783]],

        [[0.6428],
         [0.5617],
         [0.9886]],

        [[0.2350],
         [0.2097],
         [0.6549]]])
torch.Size([3, 3, 1])


`stack`: 텐서간 결합

In [22]:
x = torch.FloatTensor([1, 4])
print(x)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([1., 4.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


`cat`: 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 `dim`이 존재해야함
- 해당 차원을 늘려준 후 결합

In [25]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1, 3, 3)
print(b)
c = torch.cat([a, b], dim=0)
print(c)
print(c.shape)
print(c.size())

tensor([[[-1.1651,  2.1364, -1.2825],
         [-0.0160,  0.3221,  0.4656],
         [-0.8091,  0.1728, -1.1327]]])
tensor([[[ 0.8531, -0.0564,  0.0351],
         [-1.4576,  1.4466,  0.6299],
         [ 1.4295,  0.4672,  0.1911]]])
tensor([[[-1.1651,  2.1364, -1.2825],
         [-0.0160,  0.3221,  0.4656],
         [-0.8091,  0.1728, -1.1327]],

        [[ 0.8531, -0.0564,  0.0351],
         [-1.4576,  1.4466,  0.6299],
         [ 1.4295,  0.4672,  0.1911]]])
torch.Size([2, 3, 3])
torch.Size([2, 3, 3])


In [26]:
c = torch.cat([a, b], dim=1)
print(c)
print(c.shape)
print(c.size())

tensor([[[-1.1651,  2.1364, -1.2825],
         [-0.0160,  0.3221,  0.4656],
         [-0.8091,  0.1728, -1.1327],
         [ 0.8531, -0.0564,  0.0351],
         [-1.4576,  1.4466,  0.6299],
         [ 1.4295,  0.4672,  0.1911]]])
torch.Size([1, 6, 3])
torch.Size([1, 6, 3])


In [27]:
c = torch.cat([a, b], dim=2)
print(c)
print(c.shape)
print(c.size())

tensor([[[-1.1651,  2.1364, -1.2825,  0.8531, -0.0564,  0.0351],
         [-0.0160,  0.3221,  0.4656, -1.4576,  1.4466,  0.6299],
         [-0.8091,  0.1728, -1.1327,  1.4295,  0.4672,  0.1911]]])
torch.Size([1, 3, 6])
torch.Size([1, 3, 6])


`chunk`: 텐서를 여러 개로 나눌 때 사용 (몇 개로 나눌 것인가?)

In [30]:
tensor = torch.rand(3 ,6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim=1)    # 3개로 나누기
print(t1)
print(t2)
print(t3)

tensor([[0.9602, 0.8677, 0.3626, 0.0917, 0.8118, 0.0188],
        [0.9790, 0.7698, 0.0568, 0.9963, 0.1708, 0.0079],
        [0.1768, 0.5170, 0.1987, 0.3304, 0.2702, 0.1451]])
tensor([[0.9602, 0.8677],
        [0.9790, 0.7698],
        [0.1768, 0.5170]])
tensor([[0.3626, 0.0917],
        [0.0568, 0.9963],
        [0.1987, 0.3304]])
tensor([[0.8118, 0.0188],
        [0.1708, 0.0079],
        [0.2702, 0.1451]])


`split`: `chunk`와 동일한 기능이지만 조금 다름 (텐서의 크기는 몇인가?)

In [31]:
tensor = torch.rand(3, 6)
t1, t2 = torch.split(tensor, 3, dim=1)    # 텐서의 크기별로 나누기 
print(tensor)
print(t1)
print(t2)

tensor([[0.4520, 0.4966, 0.1233, 0.6367, 0.1745, 0.1395],
        [0.5745, 0.5736, 0.8583, 0.9193, 0.1863, 0.7425],
        [0.8701, 0.7714, 0.4776, 0.9069, 0.8066, 0.2249]])
tensor([[0.4520, 0.4966, 0.1233],
        [0.5745, 0.5736, 0.8583],
        [0.8701, 0.7714, 0.4776]])
tensor([[0.6367, 0.1745, 0.1395],
        [0.9193, 0.1863, 0.7425],
        [0.9069, 0.8066, 0.2249]])


torch ↔ numpy
- Torch Tensor(텐서)를 NumPy array(배열)로 변환 가능
  - `numpy()`
  - `from_numpy()`
- Tensor가 CPU상에 있다면 NumPy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [32]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [33]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [35]:
a.add_(1)  # a = a + 1 그냥 add하면 새로운 텐서가 생성되어서 b에 반영이 안됨
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [36]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
