### 넘파이

In [1]:
import numpy as np

In [ ]:
# 배열 
arr = np.array([1, 3, 5, 7])
print(arr) # 배열 출력
print(type(arr)) # 배열의 타입 출력
print(arr.shape) # 배열의 형태 출력
print(arr.dtype) # 배열의 데이터 타입 출력

[1 3 5 7]
<class 'numpy.ndarray'>
(4,)
int64


In [6]:
# 2차원 배열
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d) # 2차원 배열 출력
print(type(arr2d)) # 2차원 배열의 타입 출력
print(arr2d.shape) # 2차원 배열의 형태 출력
print(arr2d.dtype) # 2차원 배열의 데이터 타입 출력  

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
int64


배열 생성

In [7]:
# 배열 생성 
arr_zeros = np.zeros((2, 3)) # 2x3 배열 생성
print(arr_zeros) # 0으로 채워진 배열 출력
arr_ones = np.ones((2, 3)) # 2x3 배열 생성
print(arr_ones) # 1로 채워진 배열 출력

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 랜덤 배열 생성
arr_random = np.random.rand(2, 3) # 2x3 랜덤 배열 생성
print(arr_random) # 랜덤 배열 출력

[[0.04003565 0.60533676 0.47665872]
 [0.88654142 0.54002742 0.80659924]]


In [9]:
# 
arr = np.random.randint(5, 10, size=(2, 3)) # 5에서 10 사이의 랜덤 정수로 채워진 2x3 배열 생성
print(arr) # 랜덤 정수 배열 출력

[[5 6 5]
 [6 7 5]]


In [11]:
arr1 = np.arange(1, 10, 2) # 1부터 10까지 2씩 증가하는 배열 생성
print(arr1) # 배열 출력

arr2 = np.arange(0.1, 1, 0.1) # 0.1부터 1까지 0.1씩 증가하는 배열 생성
print(arr2) # 배열 출력

[1 3 5 7 9]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


배열 연산

In [13]:
list_data = [1, 2, 3, 4, 5]

# 넘파이 배열로 변환
arr_data = np.array(list_data)
arr_data2 = np.array([1,2,3,4,5]) # 리스트를 넘파이 배열로 변환

print(arr_data * 2) # 배열 출력
print(arr_data2 * 2) # 배열 출력
print(list_data * 2) # 리스트 출력 (리스트는 요소별 곱셈이 불가능)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [15]:
data1 = np.array([1, 2, 3, 4])
print(data1) # 배열 출력

data2 = data1 > 2 # 조건에 맞는 요소를 True로 설정
print(data2) # 조건에 맞는 요소 출력

filtered_data = data1[data2] # 조건에 맞는 요소만 추출
print(filtered_data) # 필터링된 데이터 출력

[1 2 3 4]
[False False  True  True]
[3 4]
