In [2]:
import torch

### Scalar

In [3]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [4]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


In [6]:
add_scalar = scalar1 + scalar2
print(add_scalar)

sub_scalar = scalar1 - scalar2
print(sub_scalar)

mul_scalar = scalar1 * scalar2
print(mul_scalar)

div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


In [8]:
torch.add(scalar1, scalar2)
torch.sub(scalar1, scalar2)
torch.mul(scalar1, scalar2)
torch.div(scalar1, scalar2)

tensor([0.3333])

### Vector

In [10]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [11]:
add_vector = vector1 + vector2
print(add_vector)
sub_vector = vector1 - vector2
print(sub_vector)
mul_vector = vector1 * vector2
print(mul_vector)
div_vector = vector1 / vector2
print(div_vector)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


In [13]:
torch.add(vector1, vector2)
torch.sub(vector1, vector2)
torch.mul(vector1, vector2)
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

In [14]:
torch.dot(vector1, vector2)

tensor(32.)

### Matrix

In [15]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [17]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)
sub_matrix = matrix1 - matrix2
print(sub_matrix)
mul_matrix = matrix1 * matrix2
print(mul_matrix)
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [19]:
torch.add(matrix1, matrix2)
torch.sub(matrix1, matrix2)
torch.mul(matrix1, matrix2)
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [20]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

### Tensor

In [21]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [22]:
add_tensor = tensor1 + tensor2
print(add_tensor)
sub_tensor = tensor1 - tensor2
print(sub_tensor)
mul_tensor = tensor1 * tensor2
print(mul_tensor)
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [24]:
torch.add(tensor1, tensor2)
torch.sub(tensor1, tensor2)
torch.mul(tensor1, tensor2)
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [ ]:
torch.matmul(tensor1, tensor2)  # 텐서 간 행렬 곱셈

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])